// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// impute_blocks_eigen_cpp
Rcpp::List impute_blocks_eigen_cpp(Rcpp::CharacterVector files, Rcpp::List typed_index, Rcpp::List z, Rcpp::List n_typed, Rcpp::NumericVector n_missing, double thresh, int threads, bool return_w, bool want_ld);
RcppExport SEXP _SBayesEigen_impute_blocks_eigen_cpp(SEXP filesSEXP, SEXP typed_indexSEXP, SEXP zSEXP, SEXP n_typedSEXP, SEXP n_missingSEXP, SEXP threshSEXP, SEXP threadsSEXP, SEXP return_wSEXP, SEXP want_ldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type typed_index(typed_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type n_typed(n_typedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_missing(n_missingSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_w(return_wSEXP);
    Rcpp::traits::input_parameter< bool >::type want_ld(want_ldSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_blocks_eigen_cpp(files, typed_index, z, n_typed, n_missing, thresh, threads, return_w, want_ld));
    return rcpp_result_gen;
END_RCPP
}
// ld_build_cpp
Rcpp::List ld_build_cpp(std::string geno, bool pgen, int n_samples, Rcpp::IntegerVector allele_ct, Rcpp::List blocks, Rcpp::CharacterVector out_files, double cut, int threads);
RcppExport SEXP _SBayesEigen_ld_build_cpp(SEXP genoSEXP, SEXP pgenSEXP, SEXP n_samplesSEXP, SEXP allele_ctSEXP, SEXP blocksSEXP, SEXP out_filesSEXP, SEXP cutSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< bool >::type pgen(pgenSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type allele_ct(allele_ctSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type out_files(out_filesSEXP);
    Rcpp::traits::input_parameter< double >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ld_build_cpp(geno, pgen, n_samples, allele_ct, blocks, out_files, cut, threads));
    return rcpp_result_gen;
END_RCPP
}
// tidy_cpp
Rcpp::List tidy_cpp(std::string mafile, std::string snpinfo, std::string output, double freq_thresh, double N_sd_range, double rate2pq, bool want_strings, int threads);
RcppExport SEXP _SBayesEigen_tidy_cpp(SEXP mafileSEXP, SEXP snpinfoSEXP, SEXP outputSEXP, SEXP freq_threshSEXP, SEXP N_sd_rangeSEXP, SEXP rate2pqSEXP, SEXP want_stringsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mafile(mafileSEXP);
    Rcpp::traits::input_parameter< std::string >::type snpinfo(snpinfoSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< double >::type freq_thresh(freq_threshSEXP);
    Rcpp::traits::input_parameter< double >::type N_sd_range(N_sd_rangeSEXP);
    Rcpp::traits::input_parameter< double >::type rate2pq(rate2pqSEXP);
    Rcpp::traits::input_parameter< bool >::type want_strings(want_stringsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tidy_cpp(mafile, snpinfo, output, freq_thresh, N_sd_range, rate2pq, want_strings, threads));
    return rcpp_result_gen;
END_RCPP
}
// eig_beta_cpp
List eig_beta_cpp(CharacterVector files, List alpha, double thresh, int threads);
RcppExport SEXP _SBayesEigen_eig_beta_cpp(SEXP filesSEXP, SEXP alphaSEXP, SEXP threshSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< List >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(eig_beta_cpp(files, alpha, thresh, threads));
    return rcpp_result_gen;
END_RCPP
}
// em_step_cpp
List em_step_cpp(NumericVector w, NumericVector c, NumericVector n, NumericVector gamma, NumericVector pi, double sigma2, double ve, double s2p, double nu, double A0, int threads);
RcppExport SEXP _SBayesEigen_em_step_cpp(SEXP wSEXP, SEXP cSEXP, SEXP nSEXP, SEXP gammaSEXP, SEXP piSEXP, SEXP sigma2SEXP, SEXP veSEXP, SEXP s2pSEXP, SEXP nuSEXP, SEXP A0SEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type ve(veSEXP);
    Rcpp::traits::input_parameter< double >::type s2p(s2pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type A0(A0SEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(em_step_cpp(w, c, n, gamma, pi, sigma2, ve, s2p, nu, A0, threads));
    return rcpp_result_gen;
END_RCPP
}
// post_cpp
List post_cpp(NumericVector w, NumericVector c, NumericVector n, NumericVector gamma, NumericVector pi, double sigma2, double ve, int threads);
RcppExport SEXP _SBayesEigen_post_cpp(SEXP wSEXP, SEXP cSEXP, SEXP nSEXP, SEXP gammaSEXP, SEXP piSEXP, SEXP sigma2SEXP, SEXP veSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type ve(veSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(post_cpp(w, c, n, gamma, pi, sigma2, ve, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SBayesEigen_impute_blocks_eigen_cpp", (DL_FUNC) &_SBayesEigen_impute_blocks_eigen_cpp, 9},
    {"_SBayesEigen_ld_build_cpp", (DL_FUNC) &_SBayesEigen_ld_build_cpp, 8},
    {"_SBayesEigen_tidy_cpp", (DL_FUNC) &_SBayesEigen_tidy_cpp, 8},
    {"_SBayesEigen_eig_beta_cpp", (DL_FUNC) &_SBayesEigen_eig_beta_cpp, 4},
    {"_SBayesEigen_em_step_cpp", (DL_FUNC) &_SBayesEigen_em_step_cpp, 11},
    {"_SBayesEigen_post_cpp", (DL_FUNC) &_SBayesEigen_post_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SBayesEigen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
