// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// abc_sweep_cpp
List abc_sweep_cpp(List X, IntegerVector off, NumericVector p, NumericVector r, List role, List coef, NumericVector gammaA, NumericVector piA, double s2A, double tau, double a, bool doA, bool doC, int threads);
RcppExport SEXP _SBayesEigen_abc_sweep_cpp(SEXP XSEXP, SEXP offSEXP, SEXP pSEXP, SEXP rSEXP, SEXP roleSEXP, SEXP coefSEXP, SEXP gammaASEXP, SEXP piASEXP, SEXP s2ASEXP, SEXP tauSEXP, SEXP aSEXP, SEXP doASEXP, SEXP doCSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type off(offSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< List >::type role(roleSEXP);
    Rcpp::traits::input_parameter< List >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammaA(gammaASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piA(piASEXP);
    Rcpp::traits::input_parameter< double >::type s2A(s2ASEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< bool >::type doA(doASEXP);
    Rcpp::traits::input_parameter< bool >::type doC(doCSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(abc_sweep_cpp(X, off, p, r, role, coef, gammaA, piA, s2A, tau, a, doA, doC, threads));
    return rcpp_result_gen;
END_RCPP
}
// abj_sweep_cpp
List abj_sweep_cpp(List blk, IntegerVector off, NumericVector p, NumericVector r, List mA, List al, List gC, NumericVector gammaA, NumericVector piA, double s2A, NumericVector gammaB, NumericVector piB, double s2B, double tau, double a, int threads);
RcppExport SEXP _SBayesEigen_abj_sweep_cpp(SEXP blkSEXP, SEXP offSEXP, SEXP pSEXP, SEXP rSEXP, SEXP mASEXP, SEXP alSEXP, SEXP gCSEXP, SEXP gammaASEXP, SEXP piASEXP, SEXP s2ASEXP, SEXP gammaBSEXP, SEXP piBSEXP, SEXP s2BSEXP, SEXP tauSEXP, SEXP aSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type blk(blkSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type off(offSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< List >::type mA(mASEXP);
    Rcpp::traits::input_parameter< List >::type al(alSEXP);
    Rcpp::traits::input_parameter< List >::type gC(gCSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammaA(gammaASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piA(piASEXP);
    Rcpp::traits::input_parameter< double >::type s2A(s2ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammaB(gammaBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type piB(piBSEXP);
    Rcpp::traits::input_parameter< double >::type s2B(s2BSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(abj_sweep_cpp(blk, off, p, r, mA, al, gC, gammaA, piA, s2A, gammaB, piB, s2B, tau, a, threads));
    return rcpp_result_gen;
END_RCPP
}
// ab_beta_cpp
List ab_beta_cpp(CharacterVector files, List alpha, int threads);
RcppExport SEXP _SBayesEigen_ab_beta_cpp(SEXP filesSEXP, SEXP alphaSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< List >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ab_beta_cpp(files, alpha, threads));
    return rcpp_result_gen;
END_RCPP
}
// impute_blocks_eigen_cpp
Rcpp::List impute_blocks_eigen_cpp(Rcpp::CharacterVector files, Rcpp::List typed_index, Rcpp::List z, Rcpp::List n_typed, Rcpp::NumericVector n_missing, double thresh, int threads, bool return_w, bool want_ld, Rcpp::List rows);
RcppExport SEXP _SBayesEigen_impute_blocks_eigen_cpp(SEXP filesSEXP, SEXP typed_indexSEXP, SEXP zSEXP, SEXP n_typedSEXP, SEXP n_missingSEXP, SEXP threshSEXP, SEXP threadsSEXP, SEXP return_wSEXP, SEXP want_ldSEXP, SEXP rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type typed_index(typed_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type n_typed(n_typedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_missing(n_missingSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_w(return_wSEXP);
    Rcpp::traits::input_parameter< bool >::type want_ld(want_ldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rows(rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_blocks_eigen_cpp(files, typed_index, z, n_typed, n_missing, thresh, threads, return_w, want_ld, rows));
    return rcpp_result_gen;
END_RCPP
}
// ab_pass1_cpp
Rcpp::List ab_pass1_cpp(Rcpp::CharacterVector files, Rcpp::List typed_index, Rcpp::List z, Rcpp::List n_typed, Rcpp::NumericVector n_missing, Rcpp::List rows, int threads);
RcppExport SEXP _SBayesEigen_ab_pass1_cpp(SEXP filesSEXP, SEXP typed_indexSEXP, SEXP zSEXP, SEXP n_typedSEXP, SEXP n_missingSEXP, SEXP rowsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type typed_index(typed_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type n_typed(n_typedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_missing(n_missingSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ab_pass1_cpp(files, typed_index, z, n_typed, n_missing, rows, threads));
    return rcpp_result_gen;
END_RCPP
}
// ld_build_cpp
Rcpp::List ld_build_cpp(std::string geno, bool pgen, int n_samples, Rcpp::IntegerVector allele_ct, Rcpp::List blocks, Rcpp::CharacterVector out_files, double cut, int threads, Rcpp::List a_mask, double tolA, double mem);
RcppExport SEXP _SBayesEigen_ld_build_cpp(SEXP genoSEXP, SEXP pgenSEXP, SEXP n_samplesSEXP, SEXP allele_ctSEXP, SEXP blocksSEXP, SEXP out_filesSEXP, SEXP cutSEXP, SEXP threadsSEXP, SEXP a_maskSEXP, SEXP tolASEXP, SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< bool >::type pgen(pgenSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type allele_ct(allele_ctSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type out_files(out_filesSEXP);
    Rcpp::traits::input_parameter< double >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type a_mask(a_maskSEXP);
    Rcpp::traits::input_parameter< double >::type tolA(tolASEXP);
    Rcpp::traits::input_parameter< double >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(ld_build_cpp(geno, pgen, n_samples, allele_ct, blocks, out_files, cut, threads, a_mask, tolA, mem));
    return rcpp_result_gen;
END_RCPP
}
// tidy_cpp
Rcpp::List tidy_cpp(std::string mafile, std::string snpinfo, std::string output, double freq_thresh, double N_sd_range, double rate2pq, bool want_strings, int threads);
RcppExport SEXP _SBayesEigen_tidy_cpp(SEXP mafileSEXP, SEXP snpinfoSEXP, SEXP outputSEXP, SEXP freq_threshSEXP, SEXP N_sd_rangeSEXP, SEXP rate2pqSEXP, SEXP want_stringsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mafile(mafileSEXP);
    Rcpp::traits::input_parameter< std::string >::type snpinfo(snpinfoSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< double >::type freq_thresh(freq_threshSEXP);
    Rcpp::traits::input_parameter< double >::type N_sd_range(N_sd_rangeSEXP);
    Rcpp::traits::input_parameter< double >::type rate2pq(rate2pqSEXP);
    Rcpp::traits::input_parameter< bool >::type want_strings(want_stringsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tidy_cpp(mafile, snpinfo, output, freq_thresh, N_sd_range, rate2pq, want_strings, threads));
    return rcpp_result_gen;
END_RCPP
}
// eig_beta_cpp
List eig_beta_cpp(CharacterVector files, List alpha, double thresh, int threads);
RcppExport SEXP _SBayesEigen_eig_beta_cpp(SEXP filesSEXP, SEXP alphaSEXP, SEXP threshSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< List >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(eig_beta_cpp(files, alpha, thresh, threads));
    return rcpp_result_gen;
END_RCPP
}
// em_step_cpp
List em_step_cpp(NumericVector w, NumericVector c, NumericVector n, NumericVector gamma, NumericVector pi, double sigma2, double ve, double s2p, double nu, double A0, int threads);
RcppExport SEXP _SBayesEigen_em_step_cpp(SEXP wSEXP, SEXP cSEXP, SEXP nSEXP, SEXP gammaSEXP, SEXP piSEXP, SEXP sigma2SEXP, SEXP veSEXP, SEXP s2pSEXP, SEXP nuSEXP, SEXP A0SEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type ve(veSEXP);
    Rcpp::traits::input_parameter< double >::type s2p(s2pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type A0(A0SEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(em_step_cpp(w, c, n, gamma, pi, sigma2, ve, s2p, nu, A0, threads));
    return rcpp_result_gen;
END_RCPP
}
// post_cpp
List post_cpp(NumericVector w, NumericVector c, NumericVector n, NumericVector gamma, NumericVector pi, double sigma2, double ve, int threads);
RcppExport SEXP _SBayesEigen_post_cpp(SEXP wSEXP, SEXP cSEXP, SEXP nSEXP, SEXP gammaSEXP, SEXP piSEXP, SEXP sigma2SEXP, SEXP veSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type ve(veSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(post_cpp(w, c, n, gamma, pi, sigma2, ve, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SBayesEigen_abc_sweep_cpp", (DL_FUNC) &_SBayesEigen_abc_sweep_cpp, 14},
    {"_SBayesEigen_abj_sweep_cpp", (DL_FUNC) &_SBayesEigen_abj_sweep_cpp, 16},
    {"_SBayesEigen_ab_beta_cpp", (DL_FUNC) &_SBayesEigen_ab_beta_cpp, 3},
    {"_SBayesEigen_impute_blocks_eigen_cpp", (DL_FUNC) &_SBayesEigen_impute_blocks_eigen_cpp, 10},
    {"_SBayesEigen_ab_pass1_cpp", (DL_FUNC) &_SBayesEigen_ab_pass1_cpp, 7},
    {"_SBayesEigen_ld_build_cpp", (DL_FUNC) &_SBayesEigen_ld_build_cpp, 11},
    {"_SBayesEigen_tidy_cpp", (DL_FUNC) &_SBayesEigen_tidy_cpp, 8},
    {"_SBayesEigen_eig_beta_cpp", (DL_FUNC) &_SBayesEigen_eig_beta_cpp, 4},
    {"_SBayesEigen_em_step_cpp", (DL_FUNC) &_SBayesEigen_em_step_cpp, 11},
    {"_SBayesEigen_post_cpp", (DL_FUNC) &_SBayesEigen_post_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SBayesEigen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
