# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impute_blocks_eigen_cpp <- function(files, typed_index, z, n_typed, n_missing, thresh, threads, return_w) {
    .Call(`_SBayesEigen_impute_blocks_eigen_cpp`, files, typed_index, z, n_typed, n_missing, thresh, threads, return_w)
}

ld_build_cpp <- function(geno, pgen, n_samples, allele_ct, blocks, out_files, cut, threads) {
    .Call(`_SBayesEigen_ld_build_cpp`, geno, pgen, n_samples, allele_ct, blocks, out_files, cut, threads)
}

tidy_cpp <- function(mafile, snpinfo, output, freq_thresh, N_sd_range, rate2pq, want_strings, threads) {
    .Call(`_SBayesEigen_tidy_cpp`, mafile, snpinfo, output, freq_thresh, N_sd_range, rate2pq, want_strings, threads)
}

eig_w_cpp <- function(files, bhat, thresh, threads) {
    .Call(`_SBayesEigen_eig_w_cpp`, files, bhat, thresh, threads)
}

eig_beta_cpp <- function(files, alpha, thresh, threads) {
    .Call(`_SBayesEigen_eig_beta_cpp`, files, alpha, thresh, threads)
}

em_step_cpp <- function(w, c, n, gamma, pi, sigma2, ve, s2p, nu, A0, threads) {
    .Call(`_SBayesEigen_em_step_cpp`, w, c, n, gamma, pi, sigma2, ve, s2p, nu, A0, threads)
}

post_cpp <- function(w, c, n, gamma, pi, sigma2, ve, threads) {
    .Call(`_SBayesEigen_post_cpp`, w, c, n, gamma, pi, sigma2, ve, threads)
}

eig_ldscore_cpp <- function(files) {
    .Call(`_SBayesEigen_eig_ldscore_cpp`, files)
}

